trigger:
- none   
parameters:
  - name: name
    type: string
    default: 'TestName'
  - name: id
    type: string
    default: '9999'
jobs:
- job: UseRuntimeParams
  displayName: 'Runtime paramaters'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Print Parameters'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Name passed at runtime: ${{ parameters.name }}"
        Write-Host "ID passed at runtime: ${{ parameters.id }}"
