trigger: none  # Disable CI trigger

schedules:
  - cron: "34 4 * * 2"
    displayName: "10:00 AM IST - Wednesday run"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SampleJob
    steps:
      - script: echo "Scheduled run triggered!"
