trigger: none  

schedules:
  - cron: "40 4 * * 2"
    displayName: "10:40 AM IST - Tuesday Run"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SampleJob
    steps:
      - script: echo "Hello Rithwik, it is triggering at scheduled time"
