trigger: none  # Disable CI trigger

schedules:
  - cron: "30 4 * * 3"
    displayName: "10:00 AM IST - Wednesday run"
    branches:
      include:
        - master
    always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SampleJob
    steps:
      - script: echo "Scheduled run triggered!"
